name: varxa_ui
version: 0.2.1
description: A button component using the angular framework.
dependencies:
  angular: any
  browser: any
  logging: any
dev_dependencies:
  guinness: any
  unittest: any
